version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - book_network

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/mydatabase"
    networks:
      - book_network
  
  catalog-service:
    build: app/mc-book-catalog
    container_name: catalog-service
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/mydatabase"
    networks:
      - book_network

  booking-service:
    build: app/mc-booking-management-service
    container_name: booking-service
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/mydatabase"
    networks:
      - book_network

networks:
  book_network:
    driver: bridge
