FROM python:3.11

WORKDIR /app

# Copiar o arquivo requirements.txt para o container
COPY requirements.txt .

# Instalar as dependências do requirements.txt
RUN pip install --no-cache-dir -r requirements.txt


# Copiar o restante do código da aplicação
COPY ./app /app

COPY wait-for-it.sh /app/
# Instalar curl (se necessário) para baixar o wait-for-it.sh
RUN apt-get update && apt-get install -y curl

# Baixar o script wait-for-it.sh
RUN curl -o /usr/local/bin/wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh \
    && chmod +x /usr/local/bin/wait-for-it.sh


EXPOSE 8002

# Usar o wait-for-it para aguardar o PostgreSQL antes de iniciar o serviço
CMD ["./wait-for-it.sh", "postgres:5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
