apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi-onboarding-chart.fullname" . }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "fastapi-onboarding-chart.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "fastapi-onboarding-chart.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
          ports:
            - containerPort: 5432
