apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-onboarding-chart.fullname" . }}-bookingservice
spec:
  type: {{ .Values.bookingservice.service.type }}
  ports:
    - port: {{ .Values.bookingservice.service.port }}
      targetPort: 80
  selector:
    app: {{ include "fastapi-onboarding-chart.fullname" . }}-bookingservice
