FROM python:3.11-slim

WORKDIR /app

COPY ./mc-bookingservice /app

COPY ./wait-for-it.sh /wait-for-it.sh

RUN chmod +x /wait-for-it.sh


RUN pip install --no-cache-dir -r requirements.txt

CMD ["bash", "/wait-for-it.sh", "postgres:5432", "--", "uvicorn", "routes.booking_routes:router", "--host", "0.0.0.0", "--port", "8002"]
