FROM python:3.11-slim

ENV DATABASE_URL="postgresql://admin:admin@10.244.1.252:5432/postgres"

WORKDIR /app

COPY ./mc-bookingservice /app

#COPY ./wait-for-it.sh /wait-for-it.sh

#RUN chmod +x /wait-for-it.sh


RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
