# Use a imagem base apropriada para o Python
FROM python:3.11-slim

# Definir o diretório de trabalho para o diretório onde o main.py está
WORKDIR /app

COPY ./wait-for-it.sh /wait-for-it.sh

RUN chmod +x /wait-for-it.sh

# Copiar os arquivos da aplicação para o container
COPY ./mc-userservice /app

# Instalar as dependências
RUN pip install --no-cache-dir -r /app/requirements.txt

# Comando para iniciar o serviço com o Uvicorn, apontando para main:app
CMD ["bash", "/wait-for-it.sh", "postgres:5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
